@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.sistema.fisioterapia.model.Asignado",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_2099530274 { 
   	label=sistema
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1510701950 { 
   	label=fisioterapia
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   Asignado1682105670[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Asignado</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   asignadoId: Long  </TD></TR>
<TR><TD ALIGN="LEFT" >-   cumplimientoEjercicio: Set&lt;Cumplimiento&gt; </TD></TR>
<TR><TD ALIGN="LEFT" >-   ejercicioId: Ejercicio  </TD></TR>
<TR><TD ALIGN="LEFT" >-   pacienteId: Usuario  </TD></TR>
<TR><TD ALIGN="LEFT" >-   repeticiones: String  </TD></TR>
<TR><TD ALIGN="LEFT" >-   series: String  </TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Cumplimiento1682105670[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Cumplimiento</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   asignadoId: Asignado </TD></TR>
<TR><TD ALIGN="LEFT" >-   cumplimientoId: Long </TD></TR>
<TR><TD ALIGN="LEFT" >-   repeticionRealizada: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   serieRealizada: String </TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Ejercicio1682105670[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Ejercicio</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   asignado: Set&lt;Asignado&gt; </TD></TR>
<TR><TD ALIGN="LEFT" >-   descripcion: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   ejercicioId: Long </TD></TR>
<TR><TD ALIGN="LEFT" >-   nombre: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   parteCuerpo: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   posicionCamaraId: PosicionCamara </TD></TR>
<TR><TD ALIGN="LEFT" >-   tipo: String </TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Lesion1682105670[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Lesion</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   antecedentes: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   evaluacion: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   lesionId: Long </TD></TR>
<TR><TD ALIGN="LEFT" >-   nombreLesion: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   pacienteId: Usuario </TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

NotaSesion1682105670[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)NotaSesion</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   notaId: Long </TD></TR>
<TR><TD ALIGN="LEFT" >-   notaSesion: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   sesionId: Sesion </TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

PosicionCamara1682105670[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PosicionCamara</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   descripcion: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   imagenUrl: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   posicionCamara: Set&lt;Ejercicio&gt; </TD></TR>
<TR><TD ALIGN="LEFT" >-   posicionCamaraId: Long </TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Rol1682105670[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Rol</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   rolId: Long </TD></TR>
<TR><TD ALIGN="LEFT" >-   rolNombre: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   usuarioRoles: Set&lt;UsuarioRol&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Sesion1682105670[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Sesion</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   Description: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   EndTime: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   Id: Long </TD></TR>
<TR><TD ALIGN="LEFT" >-   StartTime: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   Subject: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   pacienteId: Usuario </TD></TR>
<TR><TD ALIGN="LEFT" >-   sesion: Set&lt;NotaSesion&gt; </TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Usuario1682105670[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Usuario</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   apellidos: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   correo: String  </TD></TR>
<TR><TD ALIGN="LEFT" >-   fechaNac: String  </TD></TR>
<TR><TD ALIGN="LEFT" >-   lesionId: Set&lt;Lesion&gt;  </TD></TR>
<TR><TD ALIGN="LEFT" >-   nombres: String  </TD></TR>
<TR><TD ALIGN="LEFT" >-   pacienteId: Set&lt;Sesion&gt;  </TD></TR>
<TR><TD ALIGN="LEFT" >-   password: String </TD></TR>
<TR><TD ALIGN="LEFT" >-   tokenpassword: String  </TD></TR>
<TR><TD ALIGN="LEFT" >-   username: String  </TD></TR>
<TR><TD ALIGN="LEFT" >-   usuarioId: Long </TD></TR>
<TR><TD ALIGN="LEFT" >-   usuarioRoles: Set&lt;UsuarioRol&gt; </TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UsuarioRol1682105670[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UsuarioRol</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   rol: Rol </TD></TR>
<TR><TD ALIGN="LEFT" >-   usuario: Usuario </TD></TR>
<TR><TD ALIGN="LEFT" >-   usuarioRolId: Long </TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
Asignado1682105670 -> Cumplimiento1682105670[label="cumplimientoEjercicio
[0..*]"];
Asignado1682105670 -> Ejercicio1682105670[label="ejercicioId
[0..1]"];
Asignado1682105670 -> Usuario1682105670[label="pacienteId
[0..1]"];
Cumplimiento1682105670 -> Asignado1682105670[label="asignadoId
[0..1]"];
Ejercicio1682105670 -> Asignado1682105670[label="asignado
[0..*]"];
Ejercicio1682105670 -> PosicionCamara1682105670[label="posicionCamaraId
[0..1]"];
Lesion1682105670 -> Usuario1682105670[label="pacienteId
[0..1]"];
NotaSesion1682105670 -> Sesion1682105670[label="sesionId
[0..1]"];
PosicionCamara1682105670 -> Ejercicio1682105670[label="posicionCamara
[0..*]"];
Rol1682105670 -> UsuarioRol1682105670[label="usuarioRoles
[0..*]"];
Sesion1682105670 -> NotaSesion1682105670[label="sesion
[0..*]"];
Sesion1682105670 -> Usuario1682105670[label="pacienteId
[0..1]"];
Usuario1682105670 -> Lesion1682105670[label="lesionId
[0..*]"];
Usuario1682105670 -> Sesion1682105670[label="pacienteId
[0..*]"];
Usuario1682105670 -> UsuarioRol1682105670[label="usuarioRoles
[0..*]"];
UsuarioRol1682105670 -> Rol1682105670[label="rol
[0..1]"];
UsuarioRol1682105670 -> Usuario1682105670[label="usuario
[0..1]"];
    
}
@enduml